version: "3.9"

services:
  backend:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    platform: linux/amd64      
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
